name: CI

on:
  push:
    branches: [ live ]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }} 

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: pm2 restart NodeApp --update-env
